# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 209)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ipAddressLabel = QtWidgets.QLabel(self.centralwidget)
        self.ipAddressLabel.setGeometry(QtCore.QRect(40, 30, 51, 16))
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 70, 47, 13))
        self.passwordLabel.setObjectName("passwordLabel")
        self.ipAddressInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ipAddressInput.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.ipAddressInput.setObjectName("ipAddressInput")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.passwordInput.setObjectName("passwordInput")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.connectButton.setObjectName("connectButton")
        self.connectionStatus = QtWidgets.QLabel(self.centralwidget)
        self.connectionStatus.setGeometry(QtCore.QRect(80, 150, 121, 20))
        self.connectionStatus.setText("")
        self.connectionStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionStatus.setObjectName("connectionStatus")
        self.hiddingButton = QtWidgets.QCheckBox(self.centralwidget)
        self.hiddingButton.setGeometry(QtCore.QRect(220, 70, 16, 17))
        self.hiddingButton.setText("")
        self.hiddingButton.setObjectName("hiddingButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client"))
        self.ipAddressLabel.setText(_translate("MainWindow", "IP Address:"))
        self.passwordLabel.setText(_translate("MainWindow", "Password :"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
