# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myServer(object):
    def setupUi(self, myServer):
        myServer.setObjectName("myServer")
        myServer.resize(260, 204)
        self.centralwidget = QtWidgets.QWidget(myServer)
        self.centralwidget.setObjectName("centralwidget")
        self.createServerPasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.createServerPasswordLabel.setGeometry(QtCore.QRect(70, 30, 121, 16))
        self.createServerPasswordLabel.setObjectName("createServerPasswordLabel")
        self.serverPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.serverPasswordInput.setGeometry(QtCore.QRect(70, 60, 121, 20))
        self.serverPasswordInput.setObjectName("serverPasswordInput")
        self.startServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.startServerButton.setGeometry(QtCore.QRect(90, 100, 81, 23))
        self.startServerButton.setObjectName("startServerButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(90, 140, 91, 16))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        myServer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(myServer)
        self.statusbar.setObjectName("statusbar")
        myServer.setStatusBar(self.statusbar)

        self.retranslateUi(myServer)
        QtCore.QMetaObject.connectSlotsByName(myServer)

    def retranslateUi(self, myServer):
        _translate = QtCore.QCoreApplication.translate
        myServer.setWindowTitle(_translate("myServer", "Server"))
        self.createServerPasswordLabel.setText(_translate("myServer", "Create Server Password"))
        self.startServerButton.setText(_translate("myServer", "Start Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myServer = QtWidgets.QMainWindow()
    ui = Ui_myServer()
    ui.setupUi(myServer)
    myServer.show()
    sys.exit(app.exec_())
